server:
  port: 0
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

#executionEngine:
#  url: http://localhost:8888

security:
  userInfoUri: http://webapi/user/me

spring:
  application:
    name: gis-service
  profiles:
    active:
      default
  datasource:
    url: jdbc:postgresql://localhost:5432/webapi
    username: ohdsi
    password: ohdsi
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 180000
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

kerberos:
  timeout: 60
  kinitPath:
  configPath: /etc/krb5.conf

cors:
  enabled: true
  allowedOrigins:
    - http://localhost:5555
    - http://localhost
    - http://arachnenetwork.com
  allowedMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowedHeaders:
    - authorization